management:
  endpoints:
    web:
      exposure:
          include: info, health, refresh, bus-refresh

server:
  port: ${port:8080}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
